### ISSUE TITLE
[Feature request] Discord Thread support

### ISSUE THREAD

**Issue by ElminsterAU** [Quote-Bot/QuoteBot#18]
Seems the bot will need an update to support Threads.

Probably will have to detect when a new thread is created in any of the channels it monitors, and automatically join it.

**Comment by Deivedux** [comment]
It's a feature we're definitely considering, though we're still waiting until discord.py's stable build will start supporting it.

We're also still not fully sure how to best implement it for everybody's convenience. Depending on how threads are designed, we might need to decide whether to automatically join or let the users make that decision. I personally can think of reasons of using threads to avoid bots getting in the way of a dedicated topic.

**Comment by JonathanFeenstra** [comment]
I managed to fix quoting in threads using the master branch version of discord.py on [my fork](https://github.com/JonathanFeenstra/QuoteBot/tree/a794f15a64fb0f18083bafc2bdfea5fb66372e08). That code is also used for the instance of the bot that's in the xEdit server, so the issue should be resolved there. For the official Quote bot instance it would probably be better to wait for an official discord.py release that supports threads.
